# Generated by Django 3.2.4 on 2021-06-30 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rate',
            new_name='Customer',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
