# Generated by Django 3.2.4 on 2021-06-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210630_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='night_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weekday_day_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weekend_rate',
        ),
    ]
