# Generated by Django 3.2.4 on 2021-07-01 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20210630_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='day_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='night_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weekday_day_rate',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='weekend_rate',
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_rate', models.IntegerField(blank=True, null=True)),
                ('night_rate', models.IntegerField(blank=True, null=True)),
                ('weekend_rate', models.IntegerField(blank=True, null=True)),
                ('weekday_day_rate', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='brand')),
            ],
        ),
    ]
