# Generated by Django 3.2.4 on 2021-07-01 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210701_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='consumption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.consumption'),
        ),
    ]
