# Generated by Django 3.2.4 on 2021-07-01 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20210701_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='consumption',
        ),
        migrations.AddField(
            model_name='consumption',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
    ]
