# Generated by Django 3.2.4 on 2021-07-01 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210701_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consumption',
            options={},
        ),
        migrations.AddField(
            model_name='consumption',
            name='customer_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer Name'),
        ),
    ]
