# Generated by Django 3.2.4 on 2021-07-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210701_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='day_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='night_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekday_day_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekend_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
