# Generated by Django 3.2.4 on 2021-07-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210701_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Consumption',
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='day_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='night_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weekday_day_rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='weekend_rate',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Consumption',
        ),
    ]
