# Generated by Django 3.2.4 on 2021-07-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20210702_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Name'),
        ),
    ]
