# Generated by Django 3.2.4 on 2021-07-03 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20210702_1651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='weekday_day_rate',
            new_name='cost_day_rate',
        ),
        migrations.AddField(
            model_name='customer',
            name='cost_night_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cost_weekend_day_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='cost_weekend_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ec_day_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ec_night_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ec_weekend_day_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='ec_weekend_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekend_day_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
