# Generated by Django 3.2.4 on 2021-07-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20210704_0037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='day_rate',
            new_name='day_rate1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='night_rate',
            new_name='day_rate2',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='weekend_day_rate',
            new_name='night_rate1',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='weekend_rate',
            new_name='night_rate2',
        ),
        migrations.AddField(
            model_name='customer',
            name='weekend_day_rate1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekend_day_rate2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekend_rate1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='weekend_rate2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
