# Generated by Django 3.2.4 on 2021-07-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20210704_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
